# Tugas Mandiri Data Wrangling

**Analisis Performa Kampanye Kupon Diskon Akhir Bulan**

Alur: **CSV POS → Neon PostgreSQL/CRM → MockAPI.io/Logistik → Merge → Analisis → Kamus Data → Validasi**.

## Persiapan

Jalankan sekali jika package belum terpasang:

`pip install pandas sqlalchemy psycopg2-binary requests`

Pastikan file `pos_transactions_dummy.csv` berada di folder notebook.

In [1]:
import os
import requests
import pandas as pd
from IPython.display import display
from sqlalchemy import create_engine, text

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 140)

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

## Konfigurasi sumber data

Ganti dua nilai berikut dengan data milik kamu. `DATABASE_URL` adalah connection string dari Neon, sedangkan `API_URL` adalah endpoint resource `/shipments` dari MockAPI.io.

In [3]:
CSV_PATH = "/content/drive/MyDrive/DATA_WRANGLING/pos_transactions_dummy.csv"

# Contoh format Neon:
# postgresql://USER:PASSWORD@HOST/DATABASE?sslmode=require
DATABASE_URL = "postgresql+psycopg2://neondb_owner:npg_gdkVTMsjl8D4@ep-delicate-waterfall-azop6gou-pooler.c-3.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"

# Contoh:
# https://68xxxxxxxxxxxxxxxx.mockapi.io/shipments
API_URL = "https://6abdcb97c4d5ac548301154d.mockapi.io/api/v1/shipments"

## Bagian A — Analisis Konseptual & Tata Kelola Data

In [4]:
# A1. Pemetaan kebutuhan bisnis menjadi kebutuhan teknis data
pemetaan_kebutuhan = pd.DataFrame([
    ["Total transaksi menggunakan kupon", "order_id", "string", "CSV POS"],
    ["Total transaksi menggunakan kupon", "coupon_code", "string", "CSV POS"],
    ["Total transaksi menggunakan kupon", "total_amount", "numeric", "CSV POS"],
    ["Profil loyalitas pelanggan", "customer_id", "string", "CSV POS + CRM"],
    ["Profil loyalitas pelanggan", "membership_level", "string", "Neon PostgreSQL / CRM"],
    ["Profil pelanggan", "gender", "string", "Neon PostgreSQL / CRM"],
    ["Profil pelanggan", "age", "integer", "Neon PostgreSQL / CRM"],
    ["Profil pelanggan", "city", "string", "Neon PostgreSQL / CRM"],
    ["Status pengiriman", "order_id", "string", "CSV POS + REST API"],
    ["Status pengiriman", "tracking_number", "string", "MockAPI.io"],
    ["Status pengiriman", "courier", "string", "MockAPI.io"],
    ["Status pengiriman", "status", "string", "MockAPI.io"],
], columns=["Kebutuhan Bisnis", "Atribut", "Tipe Data", "Sumber"])

display(pemetaan_kebutuhan)

# A2. Matriks RACI
raci = pd.DataFrame([
    ["Menentukan kebutuhan informasi bisnis", "A", "C", "I", "R"],
    ["Menentukan aturan dan tata kelola data", "A", "R", "C", "I"],
    ["Mengambil dan membersihkan data", "I", "C", "R", "I"],
    ["Mengintegrasikan CSV + SQL + API", "I", "C", "R", "I"],
    ["Analisis dan interpretasi hasil", "I", "C", "C", "R"],
    ["Menerima hasil analisis", "I", "C", "C", "R"],
], columns=[
    "Aktivitas",
    "Head of Business Strategy (Data Owner)",
    "Data Steward",
    "Tim Data Wrangling",
    "BI Analyst"
])

display(raci)

                     Kebutuhan Bisnis           Atribut Tipe Data                 Sumber
0   Total transaksi menggunakan kupon          order_id    string                CSV POS
1   Total transaksi menggunakan kupon       coupon_code    string                CSV POS
2   Total transaksi menggunakan kupon      total_amount   numeric                CSV POS
3          Profil loyalitas pelanggan       customer_id    string          CSV POS + CRM
4          Profil loyalitas pelanggan  membership_level    string  Neon PostgreSQL / CRM
5                    Profil pelanggan            gender    string  Neon PostgreSQL / CRM
6                    Profil pelanggan               age   integer  Neon PostgreSQL / CRM
7                    Profil pelanggan              city    string  Neon PostgreSQL / CRM
8                   Status pengiriman          order_id    string     CSV POS + REST API
9                   Status pengiriman   tracking_number    string             MockAPI.io
10                  Status pengiriman           courier    string             MockAPI.io
11                  Status pengiriman            status    string             MockAPI.io

                                Aktivitas Head of Business Strategy (Data Owner) Data Steward Tim Data Wrangling BI Analyst
0   Menentukan kebutuhan informasi bisnis                                      A            C                  I          R
1  Menentukan aturan dan tata kelola data                                      A            R                  C          I
2         Mengambil dan membersihkan data                                      I            C                  R          I
3        Mengintegrasikan CSV + SQL + API                                      I            C                  R          I
4         Analisis dan interpretasi hasil                                      I            C                  C          R
5                 Menerima hasil analisis                                      I            C                  C          R

## Bagian B1 — Ekstraksi Berkas CSV

In [5]:
df_pos = pd.read_csv(
    CSV_PATH,
    dtype={
        "order_id": str,
        "customer_id": str
    },
    parse_dates=["order_date"]
)

print("Jumlah baris POS:", len(df_pos))
print("\nTipe data:")
print(df_pos.dtypes)
print("\nData POS:")
display(df_pos.head())

Jumlah baris POS: 30

Tipe data:
order_id                 object
order_date       datetime64[ns]
customer_id              object
total_amount              int64
coupon_code              object
sales_channel            object
dtype: object

Data POS:

  order_id order_date customer_id  total_amount   coupon_code sales_channel
0  ORD1001 2026-09-20     CUST011         75000  AKHIRBULAN10         STORE
1  ORD1002 2026-09-21     CUST012        125000           NaN        ONLINE
2  ORD1003 2026-09-22     CUST004        450000  AKHIRBULAN20        ONLINE
3  ORD1004 2026-09-23     CUST002        350000  AKHIRBULAN10         STORE
4  ORD1005 2026-09-24     CUST007         75000  AKHIRBULAN10        ONLINE

## Bagian B2 — Koneksi & Kueri Database Neon

In [6]:
if DATABASE_URL == "PASTE_NEON_DATABASE_URL_DI_SINI":
    raise ValueError("Isi DATABASE_URL dengan connection string Neon PostgreSQL.")

if DATABASE_URL.startswith("postgres://"):
    DATABASE_URL = DATABASE_URL.replace("postgres://", "postgresql://", 1)

engine = create_engine(DATABASE_URL, pool_pre_ping=True)

query_customers = text("""
    SELECT
        customer_id,
        full_name,
        gender,
        age,
        city,
        membership_level,
        is_active,
        join_date
    FROM customers
    WHERE is_active = TRUE
""")

with engine.connect() as conn:
    df_customer = pd.read_sql(query_customers, conn)

df_customer["customer_id"] = df_customer["customer_id"].astype(str)

print("Jumlah customer aktif:", len(df_customer))
display(df_customer.head())

Jumlah customer aktif: 14

  customer_id      full_name  gender  age        city membership_level  is_active   join_date
0     CUST001   Andi Pratama    Male   24    Pemalang           Silver       True  2024-01-15
1     CUST002   Budi Santoso    Male   31       Tegal             Gold       True  2023-06-20
2     CUST003  Citra Lestari  Female   27      Brebes         Platinum       True  2022-08-10
3     CUST004  Dina Maharani  Female   29  Pekalongan             Gold       True  2023-02-11
4     CUST005    Eko Saputra    Male   35    Pemalang           Silver       True  2024-04-18

## Bagian B3 — REST API & Normalisasi JSON dari MockAPI.io

In [7]:
if not API_URL:
    raise ValueError("API_URL belum diisi.")

response = requests.get(API_URL, timeout=30)
response.raise_for_status()

json_logistik = response.json()

# GET /shipments dari MockAPI biasanya berupa list JSON.
# Kode berikut juga aman jika response dibungkus object {"shipments": [...]}
if isinstance(json_logistik, list):
    records_logistik = json_logistik
elif isinstance(json_logistik, dict) and "shipments" in json_logistik:
    records_logistik = json_logistik["shipments"]
elif isinstance(json_logistik, dict):
    records_logistik = [json_logistik]
else:
    raise ValueError("Format JSON dari API tidak dikenali.")

df_logistik = pd.json_normalize(records_logistik)

if "order_id" not in df_logistik.columns:
    raise KeyError("Kolom order_id tidak ditemukan pada response API.")

df_logistik["order_id"] = df_logistik["order_id"].astype(str)

for kolom in ["shipping_date", "estimated_delivery"]:
    if kolom in df_logistik.columns:
        df_logistik[kolom] = pd.to_datetime(df_logistik[kolom], errors="coerce")

print("Jumlah data logistik:", len(df_logistik))
display(df_logistik.head())

Jumlah data logistik: 12

  order_id tracking_number  courier      status shipping_date estimated_delivery destination.city destination.province
0  ORD1001      JNE1000001      JNE   DELIVERED    2026-09-20         2026-09-23         Pemalang          Jawa Tengah
1  ORD1002      JNT1000002      J&T     SHIPPED    2026-09-21         2026-09-24            Tegal          Jawa Tengah
2  ORD1003  SICEPAT1000003  SiCepat   DELIVERED    2026-09-22         2026-09-25           Brebes          Jawa Tengah
3  ORD1004      JNE1000004      JNE  IN_TRANSIT    2026-09-23         2026-09-26            Tegal          Jawa Tengah
4  ORD1005      JNT1000005      J&T   DELIVERED    2026-09-24         2026-09-27         Pemalang          Jawa Tengah

## Bagian B4 — Integrasi Data Multi-Sumber

**Alasan left join:** data POS menjadi basis transaksi. Semua transaksi POS tetap dipertahankan walaupun data pelanggan aktif atau data logistik tidak tersedia. Penggabungan CRM menggunakan `customer_id`, sedangkan logistik menggunakan `order_id`.

In [8]:
df_master_analisis = df_pos.merge(
    df_customer,
    on="customer_id",
    how="left",
    validate="many_to_one",
    suffixes=("", "_crm")
)

df_master_analisis = df_master_analisis.merge(
    df_logistik,
    on="order_id",
    how="left",
    validate="many_to_one",
    suffixes=("", "_logistik")
)

df_master_analisis["uses_coupon"] = (
    df_master_analisis["coupon_code"].notna()
    & df_master_analisis["coupon_code"].astype(str).str.strip().ne("")
)

print("Shape df_master_analisis:", df_master_analisis.shape)
display(df_master_analisis.head(10))

Shape df_master_analisis: (30, 21)

,order_id,order_date,customer_id,total_amount,coupon_code,sales_channel,full_name,gender,age,city,membership_level,is_active,join_date,tracking_number,courier,status,shipping_date,estimated_delivery,destination.city,destination.province,uses_coupon
0,ORD1001,2026-09-20,CUST011,75000,AKHIRBULAN10,STORE,Kartika Sari,Female,25.0,Pekalongan,Gold,True,2023-12-01,JNE1000001,JNE,DELIVERED,2026-09-20,2026-09-23,Pemalang,Jawa Tengah,True
1,ORD1002,2026-09-21,CUST012,125000,NaN,ONLINE,Lukman Hakim,Male,33.0,Pemalang,Bronze,True,2025-03-12,JNT1000002,J&T,SHIPPED,2026-09-21,2026-09-24,Tegal,Jawa Tengah,False
2,ORD1003,2026-09-22,CUST004,450000,AKHIRBULAN20,ONLINE,Dina Maharani,Female,29.0,Pekalongan,Gold,True,2023-02-11,SICEPAT1000003,SiCepat,DELIVERED,2026-09-22,2026-09-25,Brebes,Jawa Tengah,True
3,ORD1004,2026-09-23,CUST002,350000,AKHIRBULAN10,STORE,Budi Santoso,Male,31.0,Tegal,Gold,True,2023-06-20,JNE1000004,JNE,IN_TRANSIT,2026-09-23,2026-09-26,Tegal,Jawa Tengah,True
4,ORD1005,2026-09-24,CUST007,75000,AKHIRBULAN10,ONLINE,Gita Ayu,Female,23.0,Pemalang,Silver,True,2024-07-21,JNT1000005,J&T,DELIVERED,2026-09-24,2026-09-27,Pemalang,Jawa Tengah,True
5,ORD1006,2026-09-25,CUST002,125000,AKHIRBULAN20,ONLINE,Budi Santoso,Male,31.0,Tegal,Gold,True,2023-06-20,SICEPAT1000006,SiCepat,SHIPPED,2026-09-25,2026-09-28,Tegal,Jawa Tengah,True
6,ORD1007,2026-09-26,CUST009,350000,AKHIRBULAN10,STORE,Intan Permata,Female,30.0,Tegal,Gold,True,2023-09-14,JNE1000007,JNE,DELIVERED,2026-09-26,2026-09-29,Brebes,Jawa Tengah,True
7,ORD1008,2026-09-27,CUST004,125000,NaN,ONLINE,Dina Maharani,Female,29.0,Pekalongan,Gold,True,2023-02-11,JNT1000008,J&T,IN_TRANSIT,2026-09-27,2026-09-30,Tegal,Jawa Tengah,False
8,ORD1009,2026-09-28,CUST008,75000,NaN,ONLINE,Hendra Wijaya,Male,40.0,Brebes,Platinum,True,2021-11-03,JNE1000009,JNE,DELIVERED,2026-09-28,2026-10-01,Brebes,Jawa Tengah,False
9,ORD1010,2026-09-29,CUST013,450000,AKHIRBULAN20,STORE,Maya Putri,Female,28.0,Tegal,Platinum,True,2022-05-17,SICEPAT1000010,SiCepat,SHIPPED,2026-09-29,2026-10-02,Tegal,Jawa Tengah,True

## Analisis kebutuhan bisnis

In [9]:
# 1. Total transaksi yang menggunakan kupon
df_transaksi_kupon = df_master_analisis[df_master_analisis["uses_coupon"]].copy()
jumlah_transaksi_kupon = len(df_transaksi_kupon)

print("Total transaksi menggunakan kupon:", jumlah_transaksi_kupon)

# 2. Profil loyalitas pelanggan yang menggunakan kupon
profil_loyalitas = (
    df_transaksi_kupon["membership_level"]
    .fillna("TIDAK_TERSEDIA")
    .value_counts()
    .rename_axis("membership_level")
    .reset_index(name="jumlah_transaksi")
)

print("\nProfil loyalitas pengguna kupon:")
display(profil_loyalitas)

# 3. Status pengiriman transaksi berkupon
status_pengiriman = (
    df_transaksi_kupon["status"]
    .fillna("DATA_TIDAK_TERSEDIA")
    .astype(str)
    .str.upper()
)

ringkasan_status = (
    status_pengiriman
    .value_counts()
    .rename_axis("status")
    .reset_index(name="jumlah_transaksi")
)

jumlah_delivered = int((status_pengiriman == "DELIVERED").sum())
persentase_delivered = round(jumlah_delivered / jumlah_transaksi_kupon * 100, 2) if jumlah_transaksi_kupon else 0

print("\nStatus pengiriman transaksi berkupon:")
display(ringkasan_status)
print("Jumlah DELIVERED:", jumlah_delivered)
print("Persentase DELIVERED:", persentase_delivered, "%")

# Ringkasan per kode kupon
ringkasan_kupon = (
    df_transaksi_kupon
    .groupby("coupon_code", dropna=False)
    .agg(
        jumlah_transaksi=("order_id", "count"),
        total_nilai_transaksi=("total_amount", "sum")
    )
    .reset_index()
)

print("\nRingkasan berdasarkan kode kupon:")
display(ringkasan_kupon)

Total transaksi menggunakan kupon: 15

Profil loyalitas pengguna kupon:

  membership_level  jumlah_transaksi
0             Gold                10
1         Platinum                 2
2           Silver                 1
3   TIDAK_TERSEDIA                 1
4           Bronze                 1

Status pengiriman transaksi berkupon:

                status  jumlah_transaksi
0  DATA_TIDAK_TERSEDIA                 7
1            DELIVERED                 5
2              SHIPPED                 2
3           IN_TRANSIT                 1

Jumlah DELIVERED: 5
Persentase DELIVERED: 33.33 %

Ringkasan berdasarkan kode kupon:

    coupon_code  jumlah_transaksi  total_nilai_transaksi
0  AKHIRBULAN10                 7                1500000
1  AKHIRBULAN20                 8                1925000

## Bagian C1 — Otomasi Kamus Data

In [10]:
def buat_kamus_data(df):
    hasil = []

    for kolom in df.columns:
        seri = df[kolom]
        jumlah_missing = int(seri.isna().sum())
        persentase_missing = round(
            (jumlah_missing / len(df)) * 100, 2
        ) if len(df) > 0 else 0.0

        jumlah_unik = int(seri.nunique(dropna=True))
        sampel = (
            seri.dropna()
            .astype(str)
            .drop_duplicates()
            .head(3)
            .tolist()
        )

        hasil.append({
            "Nama Kolom": kolom,
            "Tipe Data Sistem (dtype)": str(seri.dtype),
            "Jumlah Missing Value": jumlah_missing,
            "Persentase Missing (%)": persentase_missing,
            "Jumlah Nilai Unik": jumlah_unik,
            "Sampel Nilai": " | ".join(sampel)
        })

    return pd.DataFrame(hasil)

kamus_data = buat_kamus_data(df_master_analisis)
display(kamus_data)

kamus_data.to_csv("kamus_data_hasil.csv", index=False)
print("File tersimpan: kamus_data_hasil.csv")

,Nama Kolom,Tipe Data Sistem (dtype),Jumlah Missing Value,Persentase Missing (%),Jumlah Nilai Unik,Sampel Nilai
0,order_id,object,0,0.00,30,ORD1001 | ORD1002 | ORD1003
1,order_date,datetime64[ns],0,0.00,11,2026-09-20 | 2026-09-21 | 2026-09-22
2,customer_id,object,0,0.00,12,CUST011 | CUST012 | CUST004
3,total_amount,int64,0,0.00,6,75000 | 125000 | 450000
4,coupon_code,object,15,50.00,2,AKHIRBULAN10 | AKHIRBULAN20
5,sales_channel,object,0,0.00,2,STORE | ONLINE
6,full_name,object,1,3.33,11,Kartika Sari | Lukman Hakim | Dina Maharani
7,gender,object,1,3.33,2,Female | Male
8,age,float64,1,3.33,11,25.0 | 33.0 | 29.0
9,city,object,1,3.33,4,Pekalongan | Pemalang | Tegal
10,membership_level,object,1,3.33,4,Gold | Bronze | Silver
11,is_active,object,1,3.33,1,True
12,join_date,object,1,3.33,11,2023-12-01 | 2025-03-12 | 2023-02-11
13,tracking_number,object,18,60.00,12,JNE1000001 | JNT1000002 | SICEPAT1000003
14,courier,object,18,60.00,3,JNE | J&T | SiCepat
15,status,object,18,60.00,3,DELIVERED | SHIPPED | IN_TRANSIT
16,shipping_date,datetime64[ns],18,60.00,11,2026-09-20 | 2026-09-21 | 2026-09-22
17,estimated_delivery,datetime64[ns],18,60.00,11,2026-09-23 | 2026-09-24 | 2026-09-25
18,destination.city,object,18,60.00,3,Pemalang | Tegal | Brebes
19,destination.province,object,18,60.00,1,Jawa Tengah
20,uses_coupon,bool,0,0.00,2,True | False

File tersimpan: kamus_data_hasil.csv

## Bagian C2 — Validasi Kualitas & Integritas

In [11]:
# 1. Primary key order_id tidak boleh duplikat
assert df_master_analisis["order_id"].notna().all(), \
    "Ditemukan order_id kosong."
assert df_master_analisis["order_id"].is_unique, \
    "Terdapat duplikasi pada order_id."
print("PASS 1: order_id unik.")

# 2. total_amount tidak boleh negatif
assert (df_master_analisis["total_amount"] >= 0).all(), \
    "Ditemukan total_amount negatif."
print("PASS 2: total_amount tidak negatif.")

# 3. order_date tidak boleh melebihi tanggal hari ini
hari_ini = pd.Timestamp.today().normalize()
assert (df_master_analisis["order_date"] <= hari_ini).all(), \
    "Ditemukan order_date di masa depan."
print("PASS 3: tidak ada order_date di masa depan.")

print("\nSemua automated assertions berhasil.")

PASS 1: order_id unik.
PASS 2: total_amount tidak negatif.
PASS 3: tidak ada order_date di masa depan.

Semua automated assertions berhasil.

## Output akhir

In [12]:
print("Jumlah transaksi POS              :", len(df_pos))
print("Jumlah transaksi pakai kupon     :", jumlah_transaksi_kupon)
print("Jumlah transaksi kupon DELIVERED:", jumlah_delivered)
print("Persentase DELIVERED             :", persentase_delivered, "%")

print("\nKolom df_master_analisis:")
print(df_master_analisis.columns.tolist())

display(df_master_analisis)

Jumlah transaksi POS              : 30
Jumlah transaksi pakai kupon     : 15
Jumlah transaksi kupon DELIVERED: 5
Persentase DELIVERED             : 33.33 %

Kolom df_master_analisis:
['order_id', 'order_date', 'customer_id', 'total_amount', 'coupon_code', 'sales_channel', 'full_name', 'gender', 'age', 'city', 'membership_level', 'is_active', 'join_date', 'tracking_number', 'courier', 'status', 'shipping_date', 'estimated_delivery', 'destination.city', 'destination.province', 'uses_coupon']

,order_id,order_date,customer_id,total_amount,coupon_code,sales_channel,full_name,gender,age,city,membership_level,is_active,join_date,tracking_number,courier,status,shipping_date,estimated_delivery,destination.city,destination.province,uses_coupon
0,ORD1001,2026-09-20,CUST011,75000,AKHIRBULAN10,STORE,Kartika Sari,Female,25.0,Pekalongan,Gold,True,2023-12-01,JNE1000001,JNE,DELIVERED,2026-09-20,2026-09-23,Pemalang,Jawa Tengah,True
1,ORD1002,2026-09-21,CUST012,125000,NaN,ONLINE,Lukman Hakim,Male,33.0,Pemalang,Bronze,True,2025-03-12,JNT1000002,J&T,SHIPPED,2026-09-21,2026-09-24,Tegal,Jawa Tengah,False
2,ORD1003,2026-09-22,CUST004,450000,AKHIRBULAN20,ONLINE,Dina Maharani,Female,29.0,Pekalongan,Gold,True,2023-02-11,SICEPAT1000003,SiCepat,DELIVERED,2026-09-22,2026-09-25,Brebes,Jawa Tengah,True
3,ORD1004,2026-09-23,CUST002,350000,AKHIRBULAN10,STORE,Budi Santoso,Male,31.0,Tegal,Gold,True,2023-06-20,JNE1000004,JNE,IN_TRANSIT,2026-09-23,2026-09-26,Tegal,Jawa Tengah,True
4,ORD1005,2026-09-24,CUST007,75000,AKHIRBULAN10,ONLINE,Gita Ayu,Female,23.0,Pemalang,Silver,True,2024-07-21,JNT1000005,J&T,DELIVERED,2026-09-24,2026-09-27,Pemalang,Jawa Tengah,True
5,ORD1006,2026-09-25,CUST002,125000,AKHIRBULAN20,ONLINE,Budi Santoso,Male,31.0,Tegal,Gold,True,2023-06-20,SICEPAT1000006,SiCepat,SHIPPED,2026-09-25,2026-09-28,Tegal,Jawa Tengah,True
6,ORD1007,2026-09-26,CUST009,350000,AKHIRBULAN10,STORE,Intan Permata,Female,30.0,Tegal,Gold,True,2023-09-14,JNE1000007,JNE,DELIVERED,2026-09-26,2026-09-29,Brebes,Jawa Tengah,True
7,ORD1008,2026-09-27,CUST004,125000,NaN,ONLINE,Dina Maharani,Female,29.0,Pekalongan,Gold,True,2023-02-11,JNT1000008,J&T,IN_TRANSIT,2026-09-27,2026-09-30,Tegal,Jawa Tengah,False
8,ORD1009,2026-09-28,CUST008,75000,NaN,ONLINE,Hendra Wijaya,Male,40.0,Brebes,Platinum,True,2021-11-03,JNE1000009,JNE,DELIVERED,2026-09-28,2026-10-01,Brebes,Jawa Tengah,False
9,ORD1010,2026-09-29,CUST013,450000,AKHIRBULAN20,STORE,Maya Putri,Female,28.0,Tegal,Platinum,True,2022-05-17,SICEPAT1000010,SiCepat,SHIPPED,2026-09-29,2026-10-02,Tegal,Jawa Tengah,True
10,ORD1011,2026-09-30,CUST007,175000,NaN,ONLINE,Gita Ayu,Female,23.0,Pemalang,Silver,True,2024-07-21,JNE1000011,JNE,DELIVERED,2026-09-30,2026-10-03,Pemalang,Jawa Tengah,False
11,ORD1012,2026-09-20,CUST003,175000,AKHIRBULAN20,ONLINE,Citra Lestari,Female,27.0,Brebes,Platinum,True,2022-08-10,JNT1000012,J&T,DELIVERED,2026-09-20,2026-09-23,Brebes,Jawa Tengah,True
12,ORD1013,2026-09-21,CUST002,225000,AKHIRBULAN10,STORE,Budi Santoso,Male,31.0,Tegal,Gold,True,2023-06-20,NaN,NaN,NaN,NaT,NaT,NaN,NaN,True
13,ORD1014,2026-09-22,CUST002,175000,NaN,ONLINE,Budi Santoso,Male,31.0,Tegal,Gold,True,2023-06-20,NaN,NaN,NaN,NaT,NaT,NaN,NaN,False
14,ORD1015,2026-09-23,CUST010,75000,NaN,ONLINE,Joko Susanto,Male,38.0,Pemalang,Silver,True,2024-02-27,NaN,NaN,NaN,NaT,NaT,NaN,NaN,False
15,ORD1016,2026-09-24,CUST012,350000,NaN,STORE,Lukman Hakim,Male,33.0,Pemalang,Bronze,True,2025-03-12,NaN,NaN,NaN,NaT,NaT,NaN,NaN,False
16,ORD1017,2026-09-25,CUST002,75000,NaN,ONLINE,Budi Santoso,Male,31.0,Tegal,Gold,True,2023-06-20,NaN,NaN,NaN,NaT,NaT,NaN,NaN,False
17,ORD1018,2026-09-26,CUST009,450000,NaN,ONLINE,Intan Permata,Female,30.0,Tegal,Gold,True,2023-09-14,NaN,NaN,NaN,NaT,NaT,NaN,NaN,False
18,ORD1019,2026-09-27,CUST010,350000,NaN,STORE,Joko Susanto,Male,38.0,Pemalang,Silver,True,2024-02-27,NaN,NaN,NaN,NaT,NaT,NaN,NaN,False
19,ORD1020,2026-09-28,CUST004,75000,AKHIRBULAN10,ONLINE,Dina Maharani,Female,29.0,Pekalongan,Gold,True,2023-02-11,NaN,NaN,NaN,NaT,NaT,NaN,NaN,True
20,ORD1021,2026-09-29,CUST011,175000,AKHIRBULAN20,ONLINE,Kartika Sari,Female,25.0,Pekalongan,Gold,True,2023-12-01,NaN,NaN,NaN,NaT,NaT,NaN,NaN,True
21,ORD1022,2026-09-30,CUST002,75000,AKHIRBULAN20,STORE,Budi Santoso,Male,31.0,Tegal,Gold,True,2023-06-20,NaN,NaN,NaN,NaT,NaT,NaN,NaN,True
22,ORD1023,2026-09-20,CUST007,225000,NaN,ONLINE,Gita Ayu,Female,23.0,Pemalang,Silver,True,2024-07-21,NaN,NaN,NaN,NaT,NaT,NaN,NaN,False
23,ORD1024,2026-09-21,CUST011,125000,NaN,ONLINE,Kartika Sari,Female,25.0,Pekalongan,Gold,True,2023-12-01,NaN,NaN,NaN,NaT,NaT,NaN,NaN,False
24,ORD1025,2026-09-22,CUST006,125000,NaN,STORE,Fajar Nugroho,Male,26.0,Tegal,Bronze,True,2025-01-09,NaN,NaN,NaN,NaT,NaT,NaN,NaN,False
25,ORD1026,2026-09-23,CUST011,450000,NaN,ONLINE,Kartika Sari,Female,25.0,Pekalongan,Gold,True,2023-12-01,NaN,NaN,NaN,NaT,NaT,NaN,NaN,False
26,ORD1027,2026-09-24,CUST015,350000,AKHIRBULAN10,ONLINE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,True
27,ORD1028,2026-09-25,CUST011,350000,AKHIRBULAN20,STORE,Kartika Sari,Female,25.0,Pekalongan,Gold,True,2023-12-01,NaN,NaN,NaN,NaT,NaT,NaN,NaN,True
28,ORD1029,2026-09-26,CUST012,125000,AKHIRBULAN20,ONLINE,Lukman Hakim,Male,33.0,Pemalang,Bronze,True,2025-03-12,NaN,NaN,NaN,NaT,NaT,NaN,NaN,True
29,ORD1030,2026-09-27,CUST008,175000,NaN,ONLINE,Hendra Wijaya,Male,40.0,Brebes,Platinum,True,2021-11-03,NaN,NaN,NaN,NaT,NaT,NaN,NaN,False